---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "vault-api-python.fullname" . }}-app
  labels:
    app: {{ include "vault-api-python.name" . }}
    chart: {{ include "vault-api-python.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  config.yaml: |
    flask:
      base:
        APP_NAME: Vault
      session:
        cookie:
          HTTPONLY: true
      swagger:
        specs_route: /swagger
        specs:
          - endpoint: apispec
            route: /apispec.json
        swagger_ui: true
      health:
        ENDPOINT_URI: /healthcheck

    # Section listing WSGI middlewares configuration
    wsgi:
      request_id:
        REQUEST_ID_HEADER: X-Request-ID

    # Section concerning logging configuration
    logging:
      LOGGING_CONFIG_PATH: ${LOGGING_CONFIG_FILE:-config/logging.default.yml}

    # Section concerning gunicorn configuration
    gunicorn:
      logging:
        logger_class: consensys_utils.gunicorn.logging.RequestIDLogger
      server-mechanics:
        pidfile: gunicorn.pid

    SWAGGER: {}

    SECRET_MANAGER:
      region_name: eu-west-1
