{{- if .Values.imageCredentials.create }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "vault-api-python.imagePullSecretName" . }}
  labels:
    app: {{ include "vault-api-python.name" . }}
    chart: {{ include "vault-api-python.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "vault-api-python.imagePullSecret" . }}
{{- end }}