---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "orchestrate-api.fullname" . }}-envmap
  labels:
    {{- include "orchestrate-api.labels" . | nindent 4 }}
data:
{{- range $key,$value := .Values.environment }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
