{{- if .Values.imageCredentials.create }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "orchestrate-api.imagePullSecretName" . }}
  labels:
    app.kubernetes.io/name: {{ include "orchestrate-api.name" . }}
    helm.sh/chart: {{ include "orchestrate-api.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "orchestrate-api.imagePullSecret" . }}
{{- end }}
