{{- if .Values.imageCredentials.create }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "orchestrate-api.imagePullSecretName" . }}
  labels:
    {{- include "orchestrate-api.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "orchestrate-api.imagePullSecret" . }}
{{- end }}
