{{- if .Values.environmentSecrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "orchestrate-api.fullname" . }}-secretmap
  labels:
    {{- include "orchestrate-api.labels" . | nindent 4 }}
type: Opaque
data:
{{- range $key,$value := .Values.environmentSecrets }}
  {{ $key }}: {{ $value | b64enc | quote }}
{{- end }}
{{- end }}
