apiVersion: v1
kind: Service
metadata:
  name: {{ include "orchestrate-api.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "orchestrate-api.name" . }}
    helm.sh/chart: {{ include "orchestrate-api.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.metrics: {{ .Values.product }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.grpc.port }}
      targetPort: grpc-svc
      protocol: TCP
      name: grpc-svc
    - port: {{ .Values.service.http.port }}
      targetPort: http-svc
      protocol: TCP
      name: http-svc
    - port: {{ .Values.service.metrics.port }}
      targetPort: http-metrics
      protocol: TCP
      name: http-metrics
  selector:
    app.kubernetes.io/name: {{ include "orchestrate-api.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.metrics: {{ .Values.product }}
