{{- if .Values.vault.provision.enabled }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "vault.fullname" . }}-provision
  labels:
    app.kubernetes.io/name: {{ include "vault.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "vault.chart" . }}
  annotations:
    helm.sh/hook-weight: "20"
    helm.sh/hook: "post-install,post-upgrade"
    helm.sh/hook-delete-policy: "hook-succeeded"
spec:
  backoffLimit: 3
  completions: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "vault.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
      annotations:
        {{- if .Values.aws.kube2iamRole }}
        iam.amazonaws.com/role: {{ .Values.aws.kube2iamRole }}
        {{- end }}
    spec:
      restartPolicy: "Never"
      serviceAccountName: "vault-server"
      containers:
        - name: vault-provision
          image: "{{ .Values.vault.provision.image.repository }}:{{ .Values.vault.provision.image.tag }}"
          imagePullPolicy: {{ .Values.vault.provision.image.pullPolicy }}
          command: ["/bin/sh", "-c"]
          args: ["/provision/vault-provision.sh"]
          env:
            - name: VAULT_ADDR
              value: "https://{{ include "vault.fullname" . }}"
            - name: VAULT_CACERT
              value: "/var/run/secrets/kubernetes.io/serviceaccount/ca.crt"
            - name: AWS_SECRET_ID
              value: "{{ .Values.vault.provision.awsSecretID }}"
            - name: AWS_DEFAULT_REGION
              value: "{{ .Values.vault.provision.awsRegion }}"
          volumeMounts:
            - name: secret
              mountPath: /secret
            - name: provision
              mountPath: /provision
      volumes:
        - name: provision
          configMap:
            name: "{{ include "vault.fullname" . }}-provision-script"
            defaultMode: 0777
        - name: secret
          emptyDir:
            medium: Memory
            sizeLimit: 1Mi
{{- end }}
