orbs:
  helm: circleci/helm@1.0.0

version: 2.1

executors:
  alpine:
    docker:
      - image: alpine

workflows:
  master:
    jobs:
      - lint


jobs:
  lint:
    executor: alpine
    steps:
      - init
      - run:
          name: helm lint
          working_directory: ./helm
          command: |
            helm lint

commands:
  init:
    description: "Install"
    steps:
      - helm/install-helm-client:
          version: v3.3.4
      - run:
          name: Install helm plugins
          command: |
            helm plugin install https://github.com/belitre/helm-push-artifactory-plugin --version v1.0.2
      - checkout:
          path: ./helm