{{- if .Values.vaultAgent.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "orchestrate-worker.fullname" . }}-vault-agent
  labels:
    app.kubernetes.io/name: {{ include "orchestrate-worker.name" . }}
    helm.sh/chart: {{ include "orchestrate-worker.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  agent-config.hcl: |
    exit_after_auth = true
    auto_auth {
      method "kubernetes" {
       mount_path = "auth/kubernetes"
       config = {
        role = "{{ .Values.vaultAgent.role }}"
       }
      }
      sink "file" {
        config = {
          path = "/vault/token/.vault-token"
        }
      }
    }

{{- end }}
