---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "orchestrate-worker.fullname" . }}-envmap
  labels:
    app.kubernetes.io/name: {{ include "orchestrate-worker.name" . }}
    helm.sh/chart: {{ include "orchestrate-worker.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
{{- range $key,$value := .Values.environment }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
