---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "orchestrate-worker.fullname" . }}
  labels:
    testImage: {{ default "null" .Values.testImage.cmd }}
    app.kubernetes.io/name: {{ include "orchestrate-worker.name" . }}
    helm.sh/chart: {{ include "orchestrate-worker.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.metrics: {{ .Values.product }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "orchestrate-worker.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.metrics: {{ .Values.product }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "orchestrate-worker.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.metrics: {{ .Values.product }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/secrets: {{ include (print $.Template.BasePath "/secret-env.yaml") . | sha256sum }}
        checksum/testworker: {{ include (print $.Template.BasePath "/test/test-worker.yaml") . | sha256sum }}
      {{- if .Values.aws.enabled }}
        iam.amazonaws.com/role: "{{ .Values.aws.IamRoleArn }}"
      {{- end }}
    spec:
      {{- if .Values.imageCredentials }}
      imagePullSecrets:
        - name: {{ include "orchestrate-worker.imagePullSecretName" . }}
      {{- end }}
      serviceAccountName: {{ include "orchestrate-worker.serviceAccountName" . }}
      {{- if .Values.vaultAgent.enabled }}
      initContainers:
        - name: vault-token
          image: "{{ .Values.vaultAgent.image.repository }}:{{ .Values.vaultAgent.image.tag }}"
          args:
            - "agent"
            - "-config"
            - "/vault/config/agent-config.hcl"
          envFrom:
            - configMapRef:
                name: {{ include "orchestrate-worker.fullname" . }}-envmap
          volumeMounts:
            - name: vault-token
              mountPath: /vault/token
            - name: vault-config
              mountPath: /vault/config
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - /go/bin/main
          args:
            - {{ .Values.cmd.name }}
            - run
          envFrom:
            - configMapRef:
                name: {{ include "orchestrate-worker.fullname" . }}-envmap
            - secretRef:
                name: {{ include "orchestrate-worker.fullname" . }}-secretmap
                optional: true
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
            - name: http-metrics
              containerPort: 8082
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /ready
              port: http-metrics
            initialDelaySeconds: 3
            periodSeconds: 3
          livenessProbe:
            httpGet:
              path: /live
              port: http-metrics
            initialDelaySeconds: 3
            periodSeconds: 3
          resources:
          {{ toYaml .Values.resources | nindent 12 }}
      {{- if .Values.vaultAgent.enabled }}
          volumeMounts:
            - name: vault-token
              mountPath: /vault/token
      {{- end }}            
      {{- if .Values.vaultAgent.enabled }}
      volumes:
        - name: vault-token
          emptyDir:
            medium: Memory
            sizeLimit: 1M
        - name: vault-config
          configMap:
            name: {{ include "orchestrate-worker.fullname" . }}-vault-agent
      {{ end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{ toYaml . | nindent 8 }}
      {{- end }}
