{{- if .Values.imageCredentials.create }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "orchestrate-worker.imagePullSecretName" . }}
  labels:
    {{- include "orchestrate-worker.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "orchestrate-worker.imagePullSecret" . }}
{{- end }}
{{- if .Values.testImageCredentials.create }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "orchestrate-worker.imagePullSecretNameTest" . }}
  labels:
    {{- include "orchestrate-worker.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "orchestrate-worker.imagePullSecretTest" . }}
{{- end }}
