{{- if .Values.environmentSecrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "core-stack-worker.fullname" . }}-secretmap
  labels:
    app.kubernetes.io/name: {{ include "core-stack-worker.name" . }}
    helm.sh/chart: {{ include "core-stack-worker.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
{{- range $key,$value := .Values.environmentSecrets }}
  {{ $key }}: {{ $value | b64enc | quote }}
{{- end }}
{{- end }}