apiVersion: v1
kind: Service
metadata:
  name: {{ include "orchestrate-worker.fullname" . }}
  labels:
    {{- include "orchestrate-worker.labels" . | nindent 4 }}
    app.metrics: {{ .Values.product }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.metrics.port }}
      targetPort: http-metrics
      protocol: TCP
      name: http-metrics
  selector:
    {{- include "orchestrate-worker.selectorLabels" . | nindent 4 }}
    app.metrics: {{ .Values.product }}
