apiVersion: v1
kind: Service
metadata:
  name: {{ include "core-stack-worker.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "core-stack-worker.name" . }}
    helm.sh/chart: {{ include "core-stack-worker.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.metrics.port }}
      targetPort: http-metrics
      protocol: TCP
      name: http-metrics
  selector:
    app.kubernetes.io/name: {{ include "core-stack-worker.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.metrics: {{ .Values.product }}